### ISSUE TITLE
@route is not recognized in app.blade.php after setting up ziggy on laravel 10

### ISSUE THREAD

**Issue by m-h-saeedi** [tighten/ziggy#690] opened 2023-11-16 11:27 UTC
### Ziggy version

1.8.1

### Laravel version

10.32.0

### Description

i use @route in my app.blade.php but i get this error

```
ReflectionException
Function () does not exist

Spatie\LaravelIgnition\Exceptions\ViewException: Function () does not exist in file /vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php on line 27

#0 /vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php(27): ReflectionFunction-&gt;__construct()
#1 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(533): Illuminate\Routing\RouteSignatureParameters::fromAction()
#2 /vendor/tightenco/ziggy/src/Ziggy.php(198): Illuminate\Routing\Route-&gt;signatureParameters()
#3 /vendor/tightenco/ziggy/src/Ziggy.php(134): Tightenco\Ziggy\Ziggy-&gt;resolveBindings()
#4 /vendor/tightenco/ziggy/src/Ziggy.php(30): Tightenco\Ziggy\Ziggy-&gt;nameKeyedRoutes()
#5 /vendor/tightenco/ziggy/src/BladeRouteGenerator.php(14): Tightenco\Ziggy\Ziggy-&gt;__construct()
```

i also use this and not diffrent
```
    @php
        echo app('Tightenco\Ziggy\BladeRouteGenerator')->generate();
    @endphp
```

### Ziggy call and context

```js
I use @routes in app.blade.php
```

### Ziggy configuration

```js
Uncaught ReferenceError: Ziggy is not defined
```

### Route definition

```php
Route::get('/', [HomeController::class, 'index'])->name('home');
```

**Comment by bakerkretzmar** [comment] 2023-11-16 15:11
This looks like an issue with your route definitions, can you share the code of your `HomeController::index` method?

Closing because I don't think this is a bug in Ziggy but feel free to share more info here or link to a reproduction and I'm happy to help debug some more!

**Closed by bakerkretzmar** 2023-11-16 15:11 UTC

**Comment by bakerkretzmar** [comment] 2023-11-17 17:23
That looks fine. The exception message looks like you might have a route missing an argument or a name or with a broken controller method. Do you have a route named `login`? Are you importing all your controller classes? Does this still happen after clearing your view and route cache?

**Comment by m-h-saeedi** [comment] 2023-11-18 07:31
yes I have login route
and imported all controller classes 
and clear cache and route
When I use version 0.9.4, it is completely the same, but when I update to the latest version or versions one, I get this problem.

**Comment by bakerkretzmar** [comment] 2023-11-18 15:39
It's one of your other routes causing an issue then. Is your app public so I can take a look? Or can you share a repo with a minimal reproduction of this issue?

**Comment by m-h-saeedi** [comment] 2023-11-19 06:49
What should I check on the route?
web.php
controller or what?

**Comment by m-h-saeedi** [comment] 2023-11-19 10:24
I solved the problem
One of the roots had a problem
Thank you for your help
