### ISSUE TITLE
Intelligently drop unnamed prefix name routes

### ISSUE THREAD

**Issue by sergiz** [tighten/ziggy#400] opened 2021-02-01 16:04 UTC
#### Description

When you make a whitelist of routes using a wildcard, all routes that have a name set will be taken into consideration, even if they don't have a full unique name.

#### Suggestion

Since https://github.com/laravel/framework/pull/31917 Laravel disregards routes that have name prefix set on them, but don't have a name set on them then, I think it makes sense that ziggy would do the same.

#### Alternatives

Instead of using a wildcard, manually specify every route you want to include.

**Comment by bakerkretzmar** [comment] 2021-02-02 03:02
Can you clarify what the issue is here? Ziggy gets its list of routes directly from Laravel on each request, so if Laravel drops non-unique route names then Ziggy should already be doing that too.

**Comment by sergiz** [comment] 2021-02-02 15:51
Laravel does that when caching the routes, not when registering them, so Ziggy gets all "prefix.without.name." routes too and includes them in its output.

**Comment by bakerkretzmar** [comment] 2021-02-05 16:31
I played around with this some more and noticed a few things, I'll share them so I don't forget and in case anyone's interested:

Take the following routes:

```php
Route::name('prefix.')->group(function () {
    Route::post('one', fn () => '');
    Route::patch('two', fn () => '');
    Route::post('three', fn () => '');
});
```

When routes are _not_ cached, this produces the following `php artisan route:list` output:

```
+--------+----------+----------+---------+---------+------------+
| Domain | Method   | URI      | Name    | Action  | Middleware |
+--------+----------+----------+---------+---------+------------+
|        | POST     | one      | prefix. | Closure | web        |
|        | POST     | three    | prefix. | Closure | web        |
|        | PATCH    | two      | prefix. | Closure | web        |
+--------+----------+----------+---------+---------+------------+
```

And Ziggy generates the following routes:

```js
{
    'prefix.': {
        uri: 'three',
        methods: ['POST']
    }
}
```

Ziggy only recognizes and outputs `/three` as a route named `prefix.`, I think because it's defined last. Because of this, Laravel's `route()` and Ziggy's `route()` actually behave the same way here: the only thing that works for either of them is `route('prefix.')` and they both return `http::localhost/three`.

When routes _are_ cached, the output of `php artisan route:list` looks like this:

```
+--------+----------+----------+------------------------------------+---------+------------+
| Domain | Method   | URI      | Name                               | Action  | Middleware |
+--------+----------+----------+------------------------------------+---------+------------+
|        | POST     | one      | prefix.                            | Closure | web        |
|        | POST     | three    | prefix.generated::LBm5KZROpMHiFcxP | Closure | web        |
|        | PATCH    | two      | prefix.generated::XnAEtXx7AHyRY0yX | Closure | web        |
+--------+----------+----------+------------------------------------+---------+------------+
```

And Ziggy generates this:

```js
{
    'prefix.': {
        uri: 'one',
        methods: ['POST']
    },
    'prefix.generated::ru3C0fzPL249mO1I': {
        uri: 'two',
        methods: ['PATCH']
    },
    'prefix.generated::ALs6F95f6y7RX7rV': {
        uri: 'three',
        methods: ['POST']
    }
}
```

In this case Ziggy outputs all three routes with their generated names. Again, both `route()` helpers behave the same way. Ziggy usually filters out unnamed routes by checking if they _start_ with `generated::`, but `/two` and `/three` in that example make it in because `generated::` is in the middle.

---

@sergiz I appreciate you pointing this out and please reply if you have more to add! I'm going to close this issue because I think we should actually leave Ziggy's current behaviour as it is, for two reasons:

**The 'correct' solution is to manually give all your routes unique names.**

From Taylor's PR:

> When we encounter routes like these, I think it is safe to make the assumption that the developer did not actually intend for them to have a name at all and likely have been unaware they were receiving a name in previous Laravel releases.

From the [Laravel 7 upgrade guide](https://laravel.com/docs/7.x/upgrade#unique-route-names):

> Even though never officially documented, previous Laravel releases allow you to define two different routes with the same name. In Laravel 7 this is no longer possible and you should always provide unique names for your routes. Routes with duplicate names can cause unexpected behavior in multiple areas of the framework.

**Prefixes may be in use in existing apps to match groups of routes.**

The reason that PR _added_ `generated::...` onto the end of the route name, preserving the prefix instead of replacing it, was to ease upgrading for people who were using the prefix to match many route names. I imagine there are at least a few people doing something similar with Ziggy's `current()` method (e.g. `route().current('prefix.*')`), and completely removing these routes would break that functionality for them.

**Closed by bakerkretzmar** 2021-02-05 16:31 UTC

**Comment by sergiz** [comment] 2021-03-03 09:27
> From Taylor's PR:
> 
> > When we encounter routes like these, I think it is safe to make the assumption that the developer did not actually intend for them to have a name at all and likely have been unaware they were receiving a name in previous Laravel releases.

Taking this in consideration, I would expect that routes without having their names set wouldn't be taken into consideration by Ziggy, since they just bloat your routes export and make the file bigger. However, that doesn't take users of route().current(...) into consideration ... But on the other hand, if the user wants to depend on route().current(...) then he would set a proper name to the route I guess.

But your research also unveiled an inconsistency. If you don't depend on the @routes helper, but actually export routes in a file and then bundle it, you maybe don't run a generate command when the routes are cached in Laravel (for example in CI). However, the routes are then cached in production.
Therefore, if I take data from your research the result would be the following:
Ziggy's route('prefix.') would point to /three (since the routes list would be generated from Laravel's uncached routes), while Laravel's route('prefix.') would point to /one (since routes are most likely cached in production). Moral of the story is then to always run ziggy:generate with routes cache in the same state that you will use it in production.

**Comment by bakerkretzmar** [comment] 2021-03-05 17:55
I wouldn't recommend caching routes locally actually, for any reason. Named routes should just always have unique names.
