### ISSUE TITLE
Using UUID binding with route helper

### ISSUE THREAD

**Issue by torbentschechne** [tighten/ziggy#636] opened 2023-05-05 07:40 UTC
### Ziggy version

1.5.1

### Laravel version

10.9.0

### Description

Hello,
I am in the process of migrating from Blade Templates to Inertia/Vue Templates.

I switched to routes using an UUID recently and did the following in the routes file:

```
Route::get('/{person:uuid}', ShowPersonController::class)->name('show');
```

In blade I used the route helper and just assigned the person to it. like this:

```
<a href="{{ route('person.edit', ['person' => $person]) }}
```

It worked fine.

With Inertia and Ziggy, I do the following:

```
<a :href="route('person.edit', person)">
```

But this results in a link like: `/person/160` instead of `/person/8fd219ed-f663-47a6-ac10-268ae3e5339b`

Why is this the case and how can I solve this, so that the link is using UUIDs again?

### Ziggy call and context

```js
<a :href="route('person.edit', person)">
```

### Ziggy configuration

```js
{
routes: {
person.list {
methods {
"GET"
"HEAD"
}
uri {
"person"
}
}
```

### Route definition

```php
Route::get('/{person:uuid}', ShowPersonController::class)->name('show');
```

**Comment by bakerkretzmar** [comment] 2023-05-05 13:53
How are you generating your Ziggy config? Are you using `@routes` or running `php artisan ziggy:generate`? Do you still have this issue after clearing your route and view caches and regenerating your config?

**Comment by torbentschechne** [comment] 2023-05-06 07:49
@bakerkretzmar I have not generated a Ziggy config, because Laravel Breeze came already with Ziggy support, as stated on the InertiaJS website.

<img width="662" alt="CleanShot 2023-05-06 at 09 44 52@2x" src="https://user-images.githubusercontent.com/4470136/236610819-6067bc9f-6896-4121-a3a2-3a6dca57d857.png">

I have cleared all caches, without any success. I am not using `@route()` as this can not be found in my Vue template, instead I just use `route()` as seen above. When I use @route, I get this error:

`[vite] Internal server error: Error parsing JavaScript expression: This experimental syntax requires enabling one of the following parser plugin(s): "decorators", "decorators-legacy". (1:1)`

<img width="947" alt="CleanShot 2023-05-06 at 09 49 19@2x" src="https://user-images.githubusercontent.com/4470136/236611017-d4841b29-e3c0-43ee-9d87-8758d9cb04eb.png">

**Comment by bakerkretzmar** [comment] 2023-05-06 23:43
This works as expected for me in a fresh install. There are a couple things going on here:

- For backwards compatibility reasons, if your parameter object is missing its route binding key, Ziggy will use the `id` key instead if it's there. It looks to me like what's happening here is that your JavaScript `person` object has an `id` but not a `uuid`, in which case Ziggy will not error but will return a URL that's wrong, as you observed.

- I'm not sure where you pasted that Ziggy config from but it's formatted really weirdly and doesn't match the route name in your other examples (it looks like it shows a route called `person.list`, your example route is just called `show`). Please double-check that config (just log `Ziggy.routes` in your browser console) and feel free to share a snippet of exactly what you're seeing.

Also, confusingly, the Breeze Inertia starter is using both the Vue plugin _and_ the `@routes` Blade directive. I'll dig into why and see if I need to open an issue to try to get that fixed.

If you're still having issues with this feel free to comment again! Happy to help, going to close this for now because I'm pretty sure it's not a bug in Ziggy.

**Closed by bakerkretzmar** 2023-05-06 23:43 UTC
Labels: needs more info

**Comment by torbentschechne** [comment] 2023-05-07 06:58
@bakerkretzmar Yes, that was the case. The uuid was missing, I did not recognize it when switching to Json Resources instead of returning the model directly. I am sorry that you had efforts on your side.

What I try to understand is, that Breeze must have created a Ziggy config - where can I find this config? When I need to change the config afterwards, what's the correct approach here? Should I use the `php artisan ziggy:generate` command to create a ziggy config? Is this one overwriting the config from the Breeze then?

**Comment by bakerkretzmar** [comment] 2023-05-07 20:25
No worries, happy to help!

You won't be able to find the config in your codebase because it's generated at runtime, but for that same reason you also shouldn't ever need to change it manually, it's automatically generated for you. You don't need to run `php artisan ziggy:generate`.

By default Breeze does include the `@routes` Blade directive in its default layout [here](https://github.com/laravel/breeze/blob/a7e7e2acfb2fd332183aae41c445be7a2329e93e/stubs/inertia-vue/resources/views/app.blade.php#L14), which makes the `route` function and `Ziggy` config object available globally in JavaScript. You can see the value of that config by just running `console.log(Ziggy)` in your browser console on any page.

The Ziggy config is _additionally_ generated by the `HandleInertiaRequests` middleware [here](https://github.com/laravel/breeze/blob/a7e7e2acfb2fd332183aae41c445be7a2329e93e/stubs/inertia-common/app/Http/Middleware/HandleInertiaRequests.php#L37), but that value is only actually used anywhere if you set up your app with SSR support.

Let me know if that makes sense and answers your question!
