### ISSUE TITLE
'route' is not defined (Laravel/Inertia/Svelte)

### ISSUE THREAD

**Issue by ronvdberkmortel** [tighten/ziggy#398] opened 2021-01-13 21:47 UTC
#### Description

I am using Laravel with Inertia.
I am using Svelte through laravel-mix-svelte.
I am using the Blade implementation with @routes.

I am using Ziggy to access my Laravel routes in Svelte. The function route() works as expected, both in templates and in the browser console, but when compiling my javascript I receive a warning "'route' is not defined". I suspect this might be a very easy fix, but I am unable to find anything about the combination of Svelte and Ziggy online, especially with this specific error in mind. I have not added any Ziggy-related javascript or webpack configuration. If possible, I would prefer to keep using the @routes blade directive.

The error:

```
WARNING in ./resources/js/Layouts/AppLayout.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
'route' is not defined (37:45)
```

#### Expected behavior

The route() function works fine, but it would be nice if I would no longer get the "'route' is not defined" warning when I am running 'npm run watch'.

#### Environment

- **Laravel version**: 8.21.0
- **Ziggy version**:  1.0.4

**Related routes**:

The Fortify Register route, which functions properly both in route:list and by visiting the /register URL.

**`Ziggy.routes`**:

```js
{"uri":"register","methods":["GET","HEAD"]}
```

**Ziggy call and context**:

<a use:inertia href={ route("register") } class="nav-link">Register</a>

**Comment by bakerkretzmar** [comment] 2021-01-14 00:44
Interesting, I've used Svelte before but not a lot and not with Ziggy. Just to clarify, everything _works_, right? It's just a warning in the console, but your app still builds successfully?

Does adding `const route = window.route` to the script tags of the components that use Ziggy fix it?

**Comment by ronvdberkmortel** [comment] 2021-01-14 11:22
> Interesting, I've used Svelte before but not a lot and not with Ziggy. Just to clarify, everything _works_, right? It's just a warning in the console, but your app still builds successfully?
> 
> Does adding `const route = window.route` to the script tags of the components that use Ziggy fix it?

Thanks for the quick reply!

I indeed get no errors or warnings in the browser console and the route() helper works as intended. However, when compiling through Laravel Mix, I receive warnings about route() being undefined in the components. The JS still compiles properly though.

I just tried to add `const route = window.route` to the component script, which seems to have solved the problem. Would it be possible to add something similar globally? That would prevent having to add the const to every component.

**Comment by bakerkretzmar** [comment] 2021-01-15 15:33
> Would it be possible to add something similar globally?

As far as I can tell, no, unfortunately. I could be wrong, but there doesn't seem to be a way to do that in Svelte. You could try to find some sort of plugin for it (see sveltejs/sapper#702), or refer directly to the window in your templates with something like `href={window.route('register')}`. Otherwise I think you'll have to import it everywhere.

Closing because this isn't a bug in Ziggy, but if you figure out a better way to accomplish this please let us know!

**Closed by bakerkretzmar** 2021-01-15 15:33 UTC

**Comment by sebastianfeistl** [comment] 2024-01-13 09:47
I can confirm the same warning still appears.

Adding `const route = window.route` to the start of the Svelte component that uses the `route` helper function seems to work to get rid of the warning, but a global definition would be much nicer.

However, since the thread is more than 3 years old, I'm curious if anyone has discovered a more recent or improved solution. If you have any updates or better alternatives, I would greatly appreciate it. Thanks!

**Comment by harryqt** [comment] 2025-04-24 19:18
Did anyone figured out a better solution?

**Comment by sebastianfeistl** [comment] 2025-04-28 08:12
@harryqt Just wanted to share what worked for me:

I created a `ziggy.d.ts` file with the following content:

```ts
// ziggy.d.ts
declare function route(name: string, params?: any): string;
```

This got rid of the "_route is not defined_" warning during compilation for me, without having to add `const route = window.route` in every Svelte component.

Not sure if this will work for everyone, but maybe it helps!
