### ISSUE TITLE
export 'ZiggyVue' (imported as 'ZiggyVue') was not found in 'ziggy' (module has no exports)

### ISSUE THREAD

**Issue by plweil** [tighten/ziggy#479] opened 2021-12-01 16:16 UTC
### Ziggy version

v1.4.2

### Laravel version

v6.20.26

### Description

Also using Vue,js v.2.6.11 and Laravel Mix mix v6.0.32

I also ran the artisan command to generate the ziggy.js file in /resources/js

### Ziggy call and context

```js
I just installed Ziggy and am testing it out in a Vue component. When I run `npm run dev`, I get

`export 'ZiggyVue' (imported as 'ZiggyVue') was not found in 'ziggy' (module has no exports)`

Maybe I need a different path for the import, but I'm just following the documentation.

In my Vue component:

import { ZiggyVue } from 'ziggy';
import { Ziggy } from './ziggy';
Vue.use(ZiggyVue, Ziggy)


in webpack.mix.js:

const mix = require('laravel-mix')
const config = require('./webpack.config')
const path = require('path');
require('dotenv').config()
mix.webpackConfig(config)
require('laravel-mix-polyfill')

mix.alias({
  ziggy: path.resolve('vendor/tightenco/ziggy/dist/vue'),
})
[...]
```

### Ziggy configuration

```js
nothing relevant
```

### Route definition

```php
nothing relevant
```

**Comment by bakerkretzmar** [comment] 2021-12-01 16:46
Is your `Vue.use()` setup in your `app.js` or in a specific Vue component? What's in the `webpack.config` file?

It looks like the Mix alias isn't being recognized or isn't working. Does it work if you import it directly with something like `import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue'`?

**Comment by plweil** [comment] 2021-12-01 17:09
> It looks like the Mix alias isn't being recognized or isn't working. Does it work if you import it directly with something like `import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue'`?

Suprisingly, no. I get the same error if I import it directly using `import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue'` (which is the correct path)

> Is your `Vue.use()` setup in your `app.js` or in a specific Vue component?

The component in question is the equivalent of `app.js`.

>What's in the `webpack.config` file?

My `webpack.config.js`:

not much. Do I need add another alias for this?

```
const path = require('path')
const webpack = require('webpack')

module.exports = {

  resolve: {
    extensions: ['.js', '.json', '.vue'],
    alias: {
      '@': path.resolve(__dirname, './resources/js'),
    }
  },
}
```

**Comment by bakerkretzmar** [comment] 2021-12-01 19:21
Could the `webpack.config.js` aliases be overwriting Mix's? Try removing your `mix.alias()` call and putting the ziggy alias in the webpack config file with the `@` one.

Also, try importing `ZiggyVue` directly from a file, using the whole path as above but also including `vue.es.js` or `vue.m.js`.

If those don't work I'll try to replicate this myself, or if you can share a minimal reproduction in a repo that would be helpful.

**Comment by plweil** [comment] 2021-12-01 20:27
Adding the suffix `.es.js` works in both Mix and `webpack.config.js`. Leaving the suffix off generates the warning message mentioned above, even if I add 'es.js' to resolve.extensions.

Once this worked, I did not try importing directly with the suffix added, but I have a hunch that will work, too.

I don't quite get why it won't resolve without the suffix, and whether it has something to do with my setup or not. But at least it works now. Thanks.

**Comment by bakerkretzmar** [comment] 2021-12-01 23:59
Glad you got it working! I'll try to reproduce this as well and debug a bit more, gonna close this for now.

**Closed by bakerkretzmar** 2021-12-01 23:59 UTC
